BOX_IMAGE = "generic/ubuntu1804"
SETUP_NODES = true
NODE_COUNT = 1
NODE_IP_NW = "192.168.26."
KUBE_VERSION="1.21.1"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |l|
    l.cpus = 1
    l.memory = "2048"
  end

  config.vm.provision :shell, :path => "install-worker.sh"

  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true
  # config.vm.network "public_network"

   
  if SETUP_NODES
    (1..NODE_COUNT).each do |i|
      config.vm.define "node#{i}" do |subconfig|
        subconfig.vm.hostname = "node#{i}"
        subconfig.vm.network :private_network, ip: NODE_IP_NW + "#{i + 10}"
      end
    end
  end
end
